files: ^doc/notebooks/

repos:
  -
    repo: local
    hooks:
      -
        id: jupytext
        name: jupytext
        entry: jupytext --from ipynb --to md:myst --pre-commit
        pass_filenames: false
        language: python