[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cd_dynamax"
version = "0.3.3"
requires-python = ">=3.11"
description = "Continuous-discrete dynamical systems with JAX and related libraries."
readme = "README.md"
authors = [
    {name="Matthew Levine"}, 
    {name="Iñigo Urteaga"}
]
maintainers = [
    {name="Matthew Levine", email="matt@basis.ai"},
    {name="Iñigo Urteaga", email="iurteaga@bcamath.org"}
]

dependencies = [
    "numpy>=2.0",
    "scipy>=1.13",
    "pandas>=2.2",
    "scikit-learn>=1.5",
    "matplotlib>=3.9",
    "seaborn>=0.13",
    "pillow>=10",
    "tqdm>=4.66",
    "jax>=0.6.2",
    "jaxlib>=0.6.2",
    "optax>=0.2.2",
    "equinox>=0.13",
    "diffrax==0.6.2",
    "lineax>=0.0.8",
    "flax>=0.11",
    "blackjax>=1.2",
    "jaxopt>=0.8",
    "chex>=0.1.88",
    "distrax>=0.1.3",
    "orbax-checkpoint>=0.9",
    "etils>=1.5",
    "dm-tree>=0.1.8",
    "fastprogress>=1.0.0",
    "graphviz",
    "ipykernel",
    "orbax-checkpoint<0.11.3; sys_platform == 'win32'"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["cd_dynamax*"]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "ruff",
    "mkdocs-material>=9.7.1",
    "mkdocs>=1.6.1,<2",
    "mypy>=1.19.1",
    "mkdocs-jupyter>=0.25.1",
    "mkdocstrings-python"
]

[tool.ruff.lint]
ignore = ["F722", "E731"]  # Ignore jaxtyping shape annotation syntax errors
